// 需要哪个，引入哪个
import Vue from "vue";
import { Button , Col, Row, Switch, NavBar, Form, Field, CellGroup, Checkbox, Progress, Grid, GridItem,
Cell, Icon, Popup, List, Notify, Dialog, SwipeCell, Toast, RadioGroup, Radio, DropdownMenu, DropdownItem, 
Picker, Uploader, Tab, Tabs, PullRefresh} from 'vant'
Vue.use(Button)
Vue.use(Col)
Vue.use(Row)
Vue.use(NavBar)
Vue.use(Switch)
Vue.use(Form)
Vue.use(Field)
Vue.use(CellGroup)
Vue.use(Checkbox)
Vue.use(Progress)
Vue.use(Grid)
Vue.use(GridItem)
Vue.use(Cell)
Vue.use(Icon)
Vue.use(Popup)
Vue.use(List)
Vue.use(Notify)
Vue.use(Dialog)
Vue.use(SwipeCell)
Vue.use(Toast)
Vue.use(RadioGroup)
Vue.use(Radio)
Vue.use(DropdownMenu)
Vue.use(DropdownItem)
Vue.use(Picker)
Vue.use(Uploader)
Vue.use(Tab)
Vue.use(Tabs)
Vue.use(PullRefresh)